package com.kmwllc.lucille.core;

import com.kmwllc.lucille.message.PersistingLocalMessageManager;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

import java.util.List;

import static org.junit.Assert.*;

@RunWith(JUnit4.class)
public class RunnerTest {

  /**
   * Test an end-to-end run with a single connector that generates 1 document, and a no-op pipeline
   */
  @Test
  public void testRunnerWithSingleDoc() throws Exception {

    // run connectors and pipeline; acquire a persisting message manager that allows
    // for reviewing saved message traffic
    PersistingLocalMessageManager manager = RunUtils.runLocal("RunnerTest/singleDoc.conf");

    // confirm doc 1 sent for processing
    List<Document> docsSentForProcessing = manager.getSavedDocumentsSentForProcessing();
    assertEquals(1, docsSentForProcessing.size());
    assertEquals("1", docsSentForProcessing.get(0).getId());

    // confirm doc 1 was processed by the pipeline and sent to the destination topic
    List<Document> docsCompleted = manager.getSavedCompletedDocuments();
    assertEquals(1, docsCompleted.size());
    assertEquals("1", docsCompleted.get(0).getId());

    // confirm doc 1 was sent to solr
    List<Document> docsSentToSolr = manager.getSavedDocsSentToSolr();
    assertEquals(1, docsSentToSolr.size());
    assertEquals("1", docsSentToSolr.get(0).getId());

    // confirm that an INDEX event was sent for doc 1 and is stamped with the proper run ID
    List<Event> events = manager.getSavedEvents();
    assertEquals(1, events.size());
    assertEquals("1", events.get(0).getDocumentId());
    assertNotNull(manager.getRunId());
    assertEquals(manager.getRunId(), events.get(0).getRunId());
    assertEquals(Event.Type.INDEX, events.get(0).getType());

    // confirm that topics are empty
    assertFalse(manager.hasEvents());
    assertNull(manager.pollCompleted());
    assertNull(manager.pollDocToProcess());
    assertNull(manager.pollEvent());
  }

  /**
   * Test an end-to-end run with a single connector that generates 1 document, and a pipeline that
   * generates one child document for every incoming document
   */
  @Test
  public void testChildHandling() throws Exception {

    PersistingLocalMessageManager manager = RunUtils.runLocal("RunnerTest/singleDocSingleChild.conf");

    // confirm doc 1 sent for processing
    List<Document> docsSentForProcessing = manager.getSavedDocumentsSentForProcessing();
    assertEquals(1, docsSentForProcessing.size());
    assertEquals("1", docsSentForProcessing.get(0).getId());

    // confirm doc 1 and its child were processed by the pipeline and sent to the destination topic
    List<Document> docsCompleted = manager.getSavedCompletedDocuments();
    assertEquals(2, docsCompleted.size());

    // confirm doc 1 and its child were sent to solr
    List<Document> docsSentToSolr = manager.getSavedDocsSentToSolr();
    assertEquals(2, docsSentToSolr.size());

    // confirm that a CREATE event was sent for doc 1's child; followed by INDEX events for both docs
    List<Event> events = manager.getSavedEvents();
    assertEquals(3, events.size());
    assertEquals(Event.Type.CREATE, events.get(0).getType());
    assertEquals(Event.Type.INDEX, events.get(1).getType());
    assertEquals(Event.Type.INDEX, events.get(2).getType());

    assertNotNull(manager.getRunId());
    assertEquals(manager.getRunId(), events.get(1).getRunId());
    assertEquals(manager.getRunId(), events.get(2).getRunId());

    // confirm that topics are empty
    assertFalse(manager.hasEvents());
    assertNull(manager.pollCompleted());
    assertNull(manager.pollDocToProcess());
    assertNull(manager.pollEvent());
  }

  /**
   * Test an end-to-end run with two connectors that each generate a single document, and a no-op pipeline
   */
  @Test
  public void testTwoConnectors() throws Exception {

    // in this test we can expect that doc 1 always appears before doc 2 in all saved message traffic,
    // because doc 1 is generated by the first connector and doc 2 is generated by the second connector;
    // connectors are supposed to execute in sequence in such a way that all work from the first connector is
    // completed before the next connector starts; so in our case, we should never be seeing messages relating
    // to doc 1 by the time doc 2 is being processed

    PersistingLocalMessageManager manager = RunUtils.runLocal("RunnerTest/twoConnectors.conf");

    // confirm doc 1 sent for processing (via first connector) and doc 2 sent (via second connector)
    List<Document> docsSentForProcessing = manager.getSavedDocumentsSentForProcessing();
    assertEquals(2, docsSentForProcessing.size());
    assertEquals("1", docsSentForProcessing.get(0).getId());
    assertEquals("2", docsSentForProcessing.get(1).getId());

    // confirm both docs were processed by the pipeline and sent to the destination topic
    List<Document> docsCompleted = manager.getSavedCompletedDocuments();
    assertEquals(2, docsCompleted.size());
    assertEquals("1", docsCompleted.get(0).getId());
    assertEquals("2", docsCompleted.get(1).getId());

    // confirm both docs were sent to solr
    List<Document> docsSentToSolr = manager.getSavedDocsSentToSolr();
    assertEquals(2, docsSentToSolr.size());
    assertEquals("1", docsSentToSolr.get(0).getId());
    assertEquals("2", docsSentToSolr.get(1).getId());

    // confirm that INDEX events were sent for both docs
    List<Event> events = manager.getSavedEvents();
    assertEquals(2, events.size());
    assertEquals(Event.Type.INDEX, events.get(0).getType());
    assertEquals(Event.Type.INDEX, events.get(1).getType());
    assertEquals("1", events.get(0).getDocumentId());
    assertEquals("2", events.get(1).getDocumentId());

    assertNotNull(manager.getRunId());
    assertEquals(manager.getRunId(), events.get(0).getRunId());
    assertEquals(manager.getRunId(), events.get(1).getRunId());

    // confirm that topics are empty
    assertFalse(manager.hasEvents());
    assertNull(manager.pollCompleted());
    assertNull(manager.pollDocToProcess());
    assertNull(manager.pollEvent());
  }


}
