
connectors: [
  {
    name: "conn"
    class: "com.kmwllc.lucille.connector.FileConnector"
    paths: ["/Users/jakesquatrito/Desktop/tika-test.csv"]
    fileHandlers {
      csv {
      }
    }
  }
]

pipelines: [
  {
    name: "pipeline1"
    stages: [
      {
        name: "tika"
        class: "com.kmwllc.lucille.tika.stage.TextExtractor"
      }
    ]
  }
]

indexer: {
  class: "com.kmwllc.lucille.indexer.NopIndexer"
}