# After a release is published, this workflow builds Lucille and then pushes new "lucille" and "lucille-api"
# images to Docker Hub.
name: Release to Docker
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Application version (e.g. 9.10.1)'
        required: true
      docker_revision:
        description: 'Docker revision (e.g. 0, 1, 2)'
        required: true

env:
  release: ${{ github.event.inputs.release_version }}.${{ github.event.inputs.docker_revision }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Release version ${{ env.release }}!"

      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: |
            21
            17
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_IMAGE_TOKEN }}

      - name: Build and push (lucille-core)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: kmwtechnology/lucille:${{ env.release }}

      - name: Build and push (lucille-api)
        uses: docker/build-push-action@v6
        with:
          # needs to be run in parent dir of the API plugin to get the jars
          context: lucille-plugins/lucille-api
          file: lucille-plugins/lucille-api/Dockerfile
          push: true
          tags: kmwtechnology/lucille-api:${{ env.release }}