package com.kmwllc.lucille.callback;

import com.kmwllc.lucille.core.ConfigAccessor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.UUID;

/**
 * Invokes one or more Connectors in sequence, only starting the next Connector once all the work
 * generated by the previous Connector is fully complete.
 *
 * TODO: move callback package into core; connector implementations go in a connector package
 *
 */
public class Runner {

  private static final Logger log = LoggerFactory.getLogger(Runner.class);

  private final String runId;
  private final RunnerMessageManager runnerMessageManager;
  private boolean localMode;

  public static void main(String[] args) throws Exception {
    new Runner(false).runConnectors(true);
  }

  public Runner(boolean localMode) {
    // generate a unique ID for this run
    this.runId = UUID.randomUUID().toString();
    log.info("runId=" + runId);
    this.runnerMessageManager = localMode ? LocalMessageManager.getInstance() : new KafkaRunnerMessageManager(runId);
    this.localMode = localMode;
  }

  public void runConnectors(boolean startWorkerAndIndexer) throws Exception {

    Worker worker = null;
    Indexer indexer = null;

    if (startWorkerAndIndexer) {
      indexer = new Indexer(localMode);
      worker = new Worker(localMode);
      Thread workerThread = new Thread(worker);
      Thread indexerThread = new Thread(indexer);
      indexerThread.start();
      workerThread.start();
    }

    List<Connector> connectors = Connector.fromConfig(ConfigAccessor.loadConfig());

    // run all the connectors in sequence, only starting the next connector once all the work
    // generated by the previous connector has been completed
    for (Connector connector : connectors) {
      runConnector(connector);
    }

    if (indexer!=null) {
      indexer.terminate();
    }

    if (worker!=null) {
      worker.terminate();
    }

    runnerMessageManager.close();
  }

  public void runConnector(Connector connector) throws Exception {

    log.info("Running connector: " + connector.toString());

    Publisher publisher = new Publisher(runId, localMode);

    Thread connectorThread = new Thread(new Runnable() {
      @Override
      public void run() {
        connector.start(publisher);
      }
    });
    connectorThread.start();
    // TODO: what if it didn't start properly?

    // TODO: CONSIDER MOVING THIS INTO PUBLISHER; call publisher.waitForCompletion();
    // might want implementation of publisher that doesn't care about completion
    while (true) {
      Event event = runnerMessageManager.pollEvent();

      if (event !=null) {
        log.info("RETRIEVED EVENT: " + event);
        publisher.handleEvent(event);
      }

      // TODO: timeouts
      if (publisher.hasReceivedAllExepectedEvents() && runnerMessageManager.allEventsConsumed(runId) &&
        !connectorThread.isAlive()) {
        break;
      }

      log.info("waiting on " + publisher.countExpectedIndexEvents() + " expected index events; " +
        publisher.countExpectedCreateEvents() + " expected create events");
    }

    log.info("Work complete");
  }

}
